import Head from "next/head";
import { Inter } from "next/font/google";
import { Box, Button, FormControl, InputLabel, MenuItem, Select } from "@mui/material";
import { useState } from "react";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const [timerset, setTimer] = useState(60);
  const [difficultyLevel, setDifficultyLevel] = useState('Easy');
  const handleStartTest = () => {
    router.push({
      pathname: '/typing-test',
      query: { timerset, difficultyLevel },
    });
  };
  return (
    <>
      <Head>
        <title>Type Tester</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mainbody">
        <Box className="formContainer">
          <center><h2>Type Tester</h2></center>
          <FormControl className="formControl">
            <InputLabel id="timer-label">Timer</InputLabel>
            <Select
              labelId="timer-label"
              id="timer-select"
              defaultValue={60}
              label="Timer"
              value={timerset}
              className="select"
              onChange={(e) => setTimer(Number(e.target.value))}
            >
              <MenuItem value={60}>1 minute</MenuItem>
              <MenuItem value={300}>5 minutes</MenuItem>
              <MenuItem value={600}>10 minutes</MenuItem>
            </Select>
          </FormControl>
          <FormControl className="formControl">
            <InputLabel id="difficulty-label">Difficulty Level</InputLabel>
            <Select
              labelId="difficulty-label"
              id="difficulty-select"
              defaultValue="Easy"
              label="Difficulty Level"
              value={difficultyLevel}
              onChange={(e) => setDifficultyLevel(e.target.value as string)}
              className="select"
            >
              <MenuItem value="Easy">Easy</MenuItem>
              <MenuItem value="Medium">Medium</MenuItem>
              <MenuItem value="Hard">Hard</MenuItem>
            </Select>
          </FormControl>
          <Button variant="contained" color="primary" onClick={handleStartTest}>Start Test</Button>
        </Box>
      </main>
    </>
  );
}
